spring:
  application:
    name: mybooking-project-two
server:
  port: 8801
  servlet:
    context-path: /mybooking/project-two
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/mybooking/cloud-discovery/eureka
  instance:
    health-check-url-path: /actuator/health